name: EKS Python applications
on:
  push:
    branches: [ "main" ]

jobs:
  Templates: 
    uses: arjunpt/python-static-reusable-githubactions/.github/workflows/cicd.yml@main
    with:
      python-version: "3.10"
      requirements-path: "requirements.txt"
      test-path: "src/test/test.py"
      source-path: "src"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      KUBE_CONFIG_PROD: ${{ secrets.KUBE_CONFIG_PROD}}
